org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=advanced_turret
mod_name=\u9AD8\u7EA7\u70AE\u5854
mod_license=MIT
mod_version=1.1.0
mod_group_id=com.tian_nu.advanced_turret
mod_authors=tian_nu
mod_description=\u6A21\u5757\u5316\u591A\u70AE\u5854\u6A21\u7EC4\uFF0C\u652F\u6301\u591A\u9762\u5347\u7EA7\u3001\u667A\u80FD\u82AF\u7247\u63D2\u4EF6\u7CFB\u7EDF\u3001\u4F24\u5BB3\u9884\u6263\u534F\u8C03\u3001\u592A\u9633\u80FD\u53D1\u7535\u548C\u7EA2\u77F3\u80FD\u91CF\u8F6C\u6362\u3002\u57FA\u4E8E\u5F00\u653E\u5F0F\u70AE\u53F0\u8BBE\u8BA1\uFF0C\u589E\u52A0\u4E86\u66F4\u591A\u7269\u54C1\u3001\u529F\u80FD\u4E0E\u673A\u5236\u3002

geckolib_version=4.4.4